### ISSUE TITLE
Show spinner during initial data request

### ISSUE THREAD

**Issue by mattwigway** [conveyal/scenario-editor#52]
When we pull down the initial data for a bundle the size of the Netherlands, it can take many seconds. We should show a 'loading project' dialog. Also we should make it faster.

**Comment by abyrd** [comment]
Marked as high priority because it has given users the impression the whole system is broken. I have myself found the projects and bundles lists empty upon logging in and assumed the currently deployed version was broken, only to discover it worked several minutes later. I believe this was just due to a slow initial data download (although I've had such long lags even on a FTTH connection).

**Comment by mattwigway** [comment]
I think that something isn't getting fetched properly on initial login, a
page refresh clears it up for me. Not that that's an acceptable solution
but should guide debugging.

Matt

**Comment by trevorgerhardt** [comment]
Now that we have increment/decrement outstanding requests this should be relatively easy.

**Comment by trevorgerhardt** [comment]
Between the in/dec and project loading now done through actions this is should be complete.
