### ISSUE TITLE
After creating project, bundle list is empty

### ISSUE THREAD

**Issue by mattwigway** [conveyal/scenario-editor#80]
If you create a new project and then try to select a bundle, the bundle list is empty and you have to refresh the page.

**Comment by abyrd** [comment]
I marked this high priority because it has given users the impression the whole system is broken (not obvious that a page refresh will fix the missing bundles). @trevorgerhardt I just assigned you because you recently mentioned working through the issue list on scenario editor. Let me know if you won't have time to check this out.

**Comment by trevorgerhardt** [comment]
I believe this issue has been resolved. Please let me know if you come across it again.
